
---
# configmap for apollo-config-server-fat
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: sre
  name: configmap-apollo-config-server-fat
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://m3502i.bjgh.db.lecloud.com:3502/ApolloConfigFAT?characterEncoding=utf8
    spring.datasource.username = apolloconfig_w
    spring.datasource.password = hVxKhZ/EPR67IPwG
    eureka.port = 32880
    eureka.service.url = http://statefulset-apollo-config-server-fat-0.service-apollo-meta-server-fat:8080/eureka/,http://statefulset-apollo-config-server-fat-1.service-apollo-meta-server-fat:8080/eureka/,http://statefulset-apollo-config-server-fat-2.service-apollo-meta-server-fat:8080/eureka/

---
kind: Service
apiVersion: v1
metadata:
  namespace: sre
  name: service-apollo-meta-server-fat
  labels:
    app: service-apollo-meta-server-fat
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pod-apollo-config-server-fat
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: Service
apiVersion: v1
metadata:
  namespace: sre
  name: service-apollo-config-server-fat
  labels:
    app: service-apollo-config-server-fat
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32880
  selector:
    app: pod-apollo-config-server-fat
  type: NodePort
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  namespace: sre
  name: statefulset-apollo-config-server-fat
  labels:
    app: statefulset-apollo-config-server-fat
spec:
  serviceName: service-apollo-meta-server-fat
  replicas: 3
  selector:
    matchLabels:
      app: pod-apollo-config-server-fat
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-config-server-fat
    spec:
      nodeSelector:
        node: "apollo"
      
      volumes:
        - name: volume-configmap-apollo-config-server-fat
          configMap:
            name: configmap-apollo-config-server-fat
            items:
              - key: application-github.properties
                path: application-github.properties

      containers:
        - image: reg-sre.lecloud.com/middleware/apollo-config-server:v1.2.0
          securityContext:
            privileged: true
          #          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          name: container-apollo-config-server-fat
          ports:
            - protocol: TCP
              containerPort: 8080
          
          volumeMounts:
            - name: volume-configmap-apollo-config-server-fat
              mountPath: /apollo-config-server/config/application-github.properties
              subPath: application-github.properties
          env:
            - name: APOLLO_CONFIG_SERVICE_NAME
              value: "service-apollo-config-server-fat.sre"
          
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          
      dnsPolicy: ClusterFirst
      restartPolicy: Always